MDScreen:

	id: player_select
	name: "player_select"
	
	md_bg_color: '#344c4D'

	MDFloatLayout:

		size_hint: 1, 1
		pos_hint: {'center_x': 0.5, 'center_y': 0.5}

		MDLabel: 
			
			size_hint: 0.5, 0.05
			pos_hint: {"center_x": 0.5, "center_y": 0.87}

			font_size: '32sp'
			halign: 'center'
			color: '#FFFFFF'
			text: 'Player Select'

			md_bg_color: '#344c4D'

		MDExtendedFabButton:

			id:  player1
			name: "player1"
			size_hint: 0.3, 0.5
			pos_hint: {"center_x": 0.3, "center_y": 0.5}
			on_press: app.load_match(1)

			FitImage:
				source: 'img_data/player1_select.png'
				pos_hint: {"center_x": 0.5, "center_y": 0.5}
		
		MDLabel: 

			halign: 'center'
			font_size: '18sp'
			color: '#FFFFFF'
			size_hint: 0.5, 0.05
			md_bg_color: '#344c4D'
			text: 'Player 1: (makes first move)'
			pos_hint: {"center_x": 0.3, "center_y": 0.25}

		MDExtendedFabButton:
			id:  player2
			name: "player2"
			size_hint: 0.3, 0.5
			pos_hint: {"center_x": 0.7, "center_y": 0.5}
			on_press: app.load_match(2)

			FitImage:
				source: 'img_data/player2_select.png'
				pos_hint: {"center_x": 0.5, "center_y": 0.5}

		MDLabel: 
			
			halign: 'center'
			font_size: '18sp'
			color: '#FFFFFF'
			size_hint: 0.5, 0.05
			md_bg_color: '#344c4D'
			text: 'Player 2: (makes second move)'
			pos_hint: {"center_x": 0.7, "center_y": 0.25}
				


